<div class="ui-layout-center marges1em">
    <h2>Oups !</h2>
    <p>L'outil du challenge "ping" le serveur régulièrement.</p>
    <p>Le serveur n'a pas répondu au dernier ping !</p>
    <h2>Trois causes possibles :</h2>
    <ul>
        <li>Le serveur ne répond plus</li>
        <li>Vous avez perdu votre connexion Internet</li>
        <li>La date limite de réponse au challenge est dépassée !</li>
    </ul>
</div>
