<div id="accordeonNotationExcelExport">
    <ol>
        <li>
            <h2><span>Export des notes</span></h2>
            <div style="overflow: auto;">
                <h3>T&eacute;l&eacute;charger les notes au format Excel</h3>
                <ul>
                    <li>--&gt; <a href="challenge/notation/xls" target="_blank" title="Fichier au format XLS">Excel 97-2003</a></li>
                    <li>--&gt; <a href="challenge/notation/xlsx" target="_blank" title="Fichier au format XLSX">Excel 2007+</a></li>
                </ul>
            </div>
        </li>
    </ol>
</div>
<script type="text/javascript">
    jQuery(document).ready (function () {
        Global.setAccordion ('accordeonNotationExcelExport');
        NotationManuelle.initialize ();
    });
</script>