<div id="accordeonExportReponseClub">
    <ol>
        <li>
            <h2><span>Récupérer les réponses - fichier ZIP</span></h2>
            <div style="overflow: auto;">
                <h3>S&eacute;lectionner un club pour récupérer ses r&eacute;ponses.</h3>
                <br />
                <ul>
                        <?php
                            foreach ($this->clubs as $k => $v) {
                                echo "<li><a href='challenge/notation/zip?numero=$k'>$v</a></li>\n";
                            }
                        ?>
                </ul>
            </div>
        </li>
    </ol>
</div>
<script type="text/javascript">
    jQuery(document).ready (function () {
        Global.setAccordion ('accordeonExportReponseClub');
    });
</script>
