<?php if (! $this->fullpage): ?>
<div id="accordeonComplet">
    <ol>
        <li>
            <h2><span>Le Challenge</span></h2>
            <div style="overflow: auto;">
                <form target="_blank" action="challenge/elaboration/complet?t=<?php echo time (); ?>">
                    <input type="hidden" id="fullpage" name="fullpage" value="1" />
                    <input type="submit" class="ui-state-default ui-corner-all" value="Voir en pleine page"></input>
                </form><br />
<?php endif; ?>
                <h1><center style="font-size: 1.5em;">Challenge <?php echo $this->chalInfos ['annee']; ?><br /><br /><?php echo $this->chalInfos ['club']; ?></center></h1><br />
                <?php
                    $indices = array ();
                    $last = 0;
                    foreach ($this->arbre as $feuille) {
                        if ($last < $feuille ['level']) {
                            $indices [] = 0;
                        } elseif ($last > $feuille ['level']) {
                            while ($last > $feuille ['level']) {
                                array_pop ($indices);
                                $last--;
                            }
                        }
                        $val = array_pop ($indices);
                        $indices [] = $val + 1;
                        $last = $feuille ['level'];
                        echo "<br /><h1>" . implode ('.', $indices) . '. ' . $feuille ['title'] . "</h1><br />\n";
                        $q = $this->mquest->getQuestion ($feuille ['noeud']);
                        $f = $this->mquest->getFichiers ($feuille ['noeud']);
                        echo $this->question ($q, $f, $this->chalInfos ['statut']);
                    }
                ?>
<?php if (! $this->fullpage): ?>
            </div>
        </li>
    </ol>
</div>
<script type="text/javascript">
    jQuery(document).ready (function () {
        Global.setAccordion ('accordeonComplet');
    });
</script>
<?php endif; ?>