<div class="ui-layout-west">
    <div>
        <center>
            <span id="spanarbre"><img src='mediatheque/images/arbre.jpg' hspace="10" width='32' height='32' title="Arbre des questions" alt="Arbre"/></span>
            <span id="spanauteur"><img src='mediatheque/images/auteur.jpg' hspace="10" width='32' height='32' title="Questions par auteur" alt="Auteurs"/></span>
            <span id="spanstatut"><img src='mediatheque/images/statut.jpg' hspace="10" width='32' height='32' title="Questions par statut" alt="Statut"/></span>
        </center>
    </div>
    <div>
        <center>
            <span id="preview"><img src='mediatheque/images/imprimer.jpg' hspace="10" height="32" title="Imprimer" alt="Imprimer" /></span>
        </center>
    </div>
    <div id="questionarbre">
        <div id="questiontree"></div>
    </div>
    <div id="questionauteur">Auteur</div>
    <div id="questionstatut">Statut</div>
</div>
<div  id="layoutCenter" class="ui-layout-center">
    <div id="tabs">
        <ul>
            <li id="accueil"><a href="challenge/elaboration/accueil"><?php echo __('challenge.accueil'); ?></a></li>
        </ul>
    </div>
</div>
