<div class="ui-layout-west">
    <div>
        <center>
            <span id="preview"><img src='mediatheque/images/imprimer.jpg' hspace="10" height="32" title="Imprimer" alt="Imprimer" /></span>
        </center>
    </div>
    <div>
        <center>
            T&eacute;l&eacute;charger le bulletin r&eacute;ponse :<br />
            <a href="challenge/reponse/xls" target="_blank" title="Fichier au format XLS">Excel 97-2003</a><br />
            ou <a href="challenge/reponse/xlsx" target="_blank" title="Fichier au format XLSX">Excel 2007+</a>
        </center>
        <br />
    </div>
    <div id="questiontree"></div>
</div>
<div  id="layoutCenter" class="ui-layout-center">
    <div id="tabs">
        <ul>
            <li id="accueil"><a href="challenge/reponse/accueil"><?php echo __('challenge.accueil'); ?></a></li>
        </ul>
    </div>
</div>
