<?php if (! $this->fullpage): ?>
<div id="accordeonCorrection">
    <ol>
        <li>
            <h2><span>Correction</span></h2>
            <div style="overflow: auto;">
                <form target="_blank" method="post" action="challenge/index/reponsecorrection?t=<?php echo time (); ?>">
                    <input type="hidden" id="fullpage" name="fullpage" value="1" />
                    <input type="submit" class="ui-state-default ui-corner-all" value="Voir en pleine page"></input>
                </form><br />
<?php endif; ?>
                <h1>
                    <center style="font-size: 1.5em;">
                        Challenge <?php echo $this->chalInfos ['annee']; ?> - Correction<br />
                    </center>
                </h1><br />
                <?php
                    $indices = array ();
                    $last = 0;
                    $total = 0;
                    foreach ($this->arbre as $feuille) {
                        if ($last < $feuille ['level']) {
                            $indices [] = 0;
                        } elseif ($last > $feuille ['level']) {
                            while ($last > $feuille ['level']) {
                                $last--;
                                array_pop ($indices);
                            }
                        }
                        $val = array_pop ($indices);
                        $indices [] = $val + 1;
                        $last = $feuille ['level'];
                        echo "<br /><h1>" . implode ('.', $indices) . '. ' . $feuille ['title'] . "</h1><br />\n";
                        $q = $this->mquestion->getQuestion ($feuille ['noeud']);
                        $f = $this->mquestion->getFichiers ($feuille ['noeud']);
                        echo $this->question ($q, $f, $this->chalInfos ['statut']);
//                        if ($q ['clubreponse'] != '0') {
                            echo "<br /><p style='color:red'>Correction : </p>";
                            list ($r, $f) = $this->mquestion->getCorrectionQuestion ($feuille ['noeud']);
                            $total += $r ['note'];
                            echo $this->reponse ($r, $f);
//                        }
                    }
//                    echo "<br /><p><b>Valeur de cette correction : $total points !</b></p>";
                ?>
<?php if (! $this->fullpage): ?>
            </div>
        </li>
    </ol>
</div>
<script type="text/javascript">
    jQuery(document).ready (function () {
        Global.setAccordion ('accordeonCorrection');
    });
</script>
<?php endif; ?>
